apiVersion: v1
kind: Secret

metadata:
  name: medico-secret

type: Opaque

stringData:
  DB_HOST: postgres-service-medico
  DB_PORT: "5432"
  DB_NAME: medico_db
  DB_USER: postgres
  DB_PASSWORD: "210904"